### ISSUE TITLE
How to install and configure this on ECS

### ISSUE THREAD

**Issue by pintraj** [opsworks-co/vector-eks-s3-opensearch#6]
How to install and configure this on ECS with out EKS

**Comment by sirantd** [comment]
Hi,

This project was made for the EKS and based on the original vector helmchart. ECS doesn't support installation from Helm charts, so you must create corresponding service/task definitions for ECS using Terraform or Cloudformation. To collect logs from the ECS Fargate, you will need to run the vector agent as a sidecar container.
